name: pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: copia repositorio
        uses : actions/checkoutt@v7]

      - name: acha o arquivo python  
        run: ls -la calc.py

      - name: abrir codigo
        run: python calc.py


      